### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by tungdo0602** [AmethystAPI/Amethyst-Template#4]
-- Configuring done (0.7s)
1> [CMake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
1> [CMake] Missing variable is:
1> [CMake] CMAKE_C_COMPILE_OBJECT
1> [CMake] -- Generating done (0.0s)
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by TheFliss** [comment]
[CMakeLists.txt](https://github.com/user-attachments/files/16161758/CMakeLists.txt)
Try using this CMakeLists, everything compiles with it

**Comment by dmahonjr06** [comment]
I had this same issue. Are you using Visual Studio?

**Comment by TheFliss** [comment]
fix the 4th line like this:
project(Amethyst-Template CXX C ASM_NASM)

**Comment by tungdo0602** [comment]
> I had this same issue. Are you using Visual Studio?

Yes

**Comment by tungdo0602** [comment]
> [CMakeLists.txt](https://github.com/user-attachments/files/16161758/CMakeLists.txt) Try using this CMakeLists, everything compiles with it

Thank you it's working
